version: '3.3'
services:
  app:
    image: docker.io/library/spring:1.0.0
    container_name: spring_new
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tms
      - SPRING_DATASOURCE_USERNAME=kripanda
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
    ports:
      - '8081:8081'

  db:
    image: postgres:15.3-alpine
    container_name: postgres_15
    restart: always
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=kripanda
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres-data: