spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 5000 # in msecs
  liquibase:
    change-log: 'classpath:db-migrations/changeLog.xml'
    enabled: true

springdoc:
  #  show-actuator: true
  #  use-management-port: true
  swagger-ui:
    path: /docs.html
  #    enabled: false
  api-docs:
    path: /api/docs.yaml
#    enabled: false

jwt:
  secret: '\\_//\\_//\\_//Password!2345\\_//\\_//\\_//'
  expiration: '10m'